<?php
declare(strict_types = 1);

namespace AppBundle\Repository;

use Doctrine\ORM\EntityManager;
use Doctrine\ORM\EntityRepository;

/**
 * EmployeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmployeeRepository extends EntityRepository
{
    /**
     * @var EntityManagerInterface
     */
    public $em;

    /**
     * EmployeeRepository constructor.
     * @param EntityManager $em
     */
    public function __construct(EntityManager $em)
    {
        $this->em = $em;
    }

    /**
     * @param mixed $id
     * @return array
     */
    public function find($id):array
    {
        return $this->em
            ->createQueryBuilder('a')
            ->select('a')
            ->from('AppBundle:Employee', 'a', null)
            ->where('a.id = :id')
            ->setParameter('id', $id)
            ->getQuery()
            ->getResult();
    }
}
